//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "entry_kind_default_field")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub entry_kind_id: i32,
    #[sea_orm(unique)]
    pub entry_kind_field_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entry_kind_fields::Entity",
        from = "Column::EntryKindFieldId",
        to = "super::entry_kind_fields::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntryKindFields,
    #[sea_orm(
        belongs_to = "super::entry_kinds::Entity",
        from = "Column::EntryKindId",
        to = "super::entry_kinds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntryKinds,
}

impl Related<super::entry_kind_fields::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryKindFields.def()
    }
}

impl Related<super::entry_kinds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryKinds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
