//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize,
)]
#[sea_orm(table_name = "entry_field_values")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub entry_id: i32,
    pub entry_field_id: i32,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entries::Entity",
        from = "Column::EntryId",
        to = "super::entries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Entries,
    #[sea_orm(
        belongs_to = "super::entry_kind_fields::Entity",
        from = "Column::EntryFieldId",
        to = "super::entry_kind_fields::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntryKindFields,
}

impl Related<super::entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entries.def()
    }
}

impl Related<super::entry_kind_fields::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryKindFields.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
