//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::decks::Entity as Decks;
pub use super::entry_kind_default_field::Entity as EntryKindDefaultField;
pub use super::entry_kind_fields::Entity as EntryKindFields;
pub use super::entry_kinds::Entity as EntryKinds;
