//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::entry_tags::Entity")]
    EntryTags,
}

impl Related<super::entry_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntryTags.def()
    }
}

impl Related<super::entries::Entity> for Entity {
    fn to() -> RelationDef {
        super::entry_tags::Relation::Entries.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::entry_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
