[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }
service = { path = "../service" }
sea-orm = { version = "0.12" }
tauri = "1"
serde_json = "1"
log = "0.4.21"
